# Generated by Django 3.2.15 on 2022-09-16 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatments', '0003_auto_20220913_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss')], max_length=5)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=11)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('your_request', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_treatment', to=settings.AUTH_USER_MODEL)),
                ('treatments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments_title', to='treatments.treatment')),
            ],
        ),
    ]
