# Generated by Django 3.2.15 on 2022-09-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAppointmentModel',
        ),
    ]
