# Generated by Django 3.2.15 on 2022-09-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_bookappointmentmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookappointmentmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'Book Appointment Model'},
        ),
    ]
