# Generated by Django 3.2.15 on 2022-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_alter_bookappointmentmodel_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointmentmodel',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
