# Generated by Django 3.2.15 on 2022-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_alter_bookappointmentmodel_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointmentmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='bookappointmentmodel',
            name='email',
            field=models.EmailField(default='default value', max_length=254),
        ),
    ]
