# Generated by Django 3.2.15 on 2022-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_auto_20220918_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointmentmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
