# Generated by Django 3.2.15 on 2022-09-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0009_alter_bookappointmentmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointmentmodel',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookappointmentmodel',
            name='your_request',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
