# Generated by Django 3.2.15 on 2022-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_auto_20220919_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointmentmodel',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
