# Generated by Django 3.2.15 on 2022-09-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0013_alter_bookappointmentmodel_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointmentmodel',
            name='admin_decision',
            field=models.BooleanField(default=False),
        ),
    ]
