# Generated by Django 3.2.15 on 2022-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(default=True, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='fullname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
