# Generated by Django 3.2.15 on 2022-09-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220915_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
