# Generated by Django 3.2.15 on 2022-09-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_phone_number_contactmodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='fullname',
            new_name='name',
        ),
    ]
