# Generated by Django 3.2.15 on 2022-09-26 10:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contactmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField
            (max_length=128, region='GB'),
        ),
    ]
